### ISSUE TITLE
Overrides prevent optimizations in lazy linking.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/j2me.js#1234]
We can delay linking in the interpreter if we know the target of a virtual/static call. At the moment there can be 3 possible targets, interpreted methods, native methods, or overrides. Native targets we have to link right away, but this is easy to check for since we can just check the access flag, for all other methods we could just continue in the interpreter and avoid linking. Unfortunately, since any method can be overridden, we have to convert the method name to a JS string, generate an impl key, check against our overrides, etc.

I propose we mark all overridden methods as native in the Java sources, and get rid of the override mechanism, or am I missing something?

**Comment by andreasgal** [comment]
We are trying to avoid changing the original Java sources. However, we could write a build tool to do this if we must do it.

**Comment by mbebenita** [comment]
We have 98 overrides, the majority of which (74) appear in `string.js`. If we reland #1189, then changing the remaining sources wouldn't be a big effort.

**Comment by brendandahl** [comment]
> We are trying to avoid changing the original Java sources. However, we could write a build tool to do this if we must do it.

We have a way to do this by copying the file into our custom folder. Our lives would be simplified further if we just changed the original sources though. We'll always have the originals in the repo history if we ever need to diff them.

@andreasgal Is there a specific reason we are avoiding changing the java sources?

**Comment by marco-c** [comment]
> We have a way to do this by copying the file into our custom folder. Our lives would be simplified further if we just changed the original sources though. We'll always have the originals in the repo history if we ever need to diff them.

I think our current mechanism with the custom/ subdirectory is better. It's easier to compare the custom implementations with the reference implementation and it's also easy to have a list of all the classes we have changed.

> Is there a specific reason we are avoiding changing the java sources?

We're doing this to ensure correctness.

**Comment by brendandahl** [comment]
It sure makes reviewing new customs much harder and it creates two files which is much more error prone if you're looking at the wrong one or if you misname/move it incorrectly.  We can easily look back in logs, blame, or diff to see the original state. We have a revision control system, why not use it?

> We're doing this to ensure correctness.

Sorry, I meant this as more why do we have a custom directory. I agree we should avoiding changing them unless necessary.

**Comment by mykmelez** [comment]
> It sure makes reviewing new customs much harder and it creates two files which is much more error prone if you're looking at the wrong one or if you misname/move it incorrectly. We can easily look back in logs, blame, or diff to see the original state. We have a revision control system, why not use it?

I agree, it's a pain in the ass, especially at review time. I feel it whenever I review a changeset that adds a custom.

> Sorry, I meant this as more why do we have a custom directory. I agree we should avoiding changing them unless necessary.

I think the primary issue is distinguishing between customized and original files when hunting bugs. Customizations are prime suspects for regressing the behavior of the complex reference implementation, and we don't always catch those regressions quickly, nor realize they're regressions from customizations.

Putting customizations into the custom/ directory makes it really clear which files have been customized without having to review the history of every suspect file.

Nevertheless, to reduce the pain without losing that clarity, let's do this: instead of copying a customized file to custom/, let's `git mv` it there. Then there'll be only a single copy of the file in the repository, the diff on initial customization (and GitHub representation thereof) will be small, the build system won't care (because it copies the file to the same directory anyway, overwriting the original with the custom), and we'll still be able to compare the current version of the customized file with the original by diffing it against its initial commit.

**Comment by marco-c** [comment]
I'm going to remove the overrides.
