### ISSUE TITLE
Handle downloading the closure compiler like the other build tools

### ISSUE THREAD

**Issue by marco-c** [mozilla/j2me.js#1328]
Currently we're downloading it in tools/ and we don't have a way to update it easily (we should handle its download like with SlimerJS or XULRunner).
We should also download it in build_tools/, this way Travis will cache it.

**Comment by mykmelez** [comment]
Note that we're using a modified version of Closure that is fairly out-of-date, built a couple months ago from [my fork](https://github.com/mykmelez/closure-compiler) of [@mbebenita's fork](https://github.com/mbebenita/closure-compiler) of the [upstream repo](https://github.com/google/closure-compiler). There have been several date-based releases to Closure since we forked, according to the [release notes](https://github.com/google/closure-compiler/wiki/Releases).

The build is also slightly out-of-date with @mbebenita's fork, which now has an additional feature from @tobytailor ([support inlining simple methods annotated with @inline](https://github.com/google/closure-compiler/commit/da0a11fd8470beab51a4f179b4af71b2c517a924)).
